# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcserver.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "grpcserver.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10grpcserver.proto"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\nGrpcServer\x12\x36\n\x11GetServerResponse\x12\x0f.MessageRequest\x1a\x10.MessageResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "grpcserver_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MESSAGERESPONSE"]._serialized_start = 20
    _globals["_MESSAGERESPONSE"]._serialized_end = 72
    _globals["_MESSAGEREQUEST"]._serialized_start = 74
    _globals["_MESSAGEREQUEST"]._serialized_end = 107
    _globals["_GRPCSERVER"]._serialized_start = 109
    _globals["_GRPCSERVER"]._serialized_end = 177
# @@protoc_insertion_point(module_scope)
